version: 2
plugins:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 18
  flog:
      enabled: true
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
exclude_patterns:
  - "spec/app"
  - "gemfiles"