language: ruby
cache: bundler
sudo: false
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - truffleruby
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/sinatra.gemfile
matrix:
  exclude:
    # Bundler 2.x coming with Ruby 2.7 does not work well with rails 4.2
    - rvm: 2.7.0
      gemfile: gemfiles/rails_4.2.gemfile
    # TruffleRuby does not seem to work with Rails
    - rvm: truffleruby
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: truffleruby
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: truffleruby
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: truffleruby
      gemfile: gemfiles/rails_5.2.gemfile
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
script:
  - bundle exec rspec
addons:
  code_climate:
    repo_token: e233a382471f480a061ac3098edadbb91cee8129e0938973aeb2aa8d84a0a93b
after_success:
  - bundle exec codeclimate-test-reporter
