language: ruby
cache: bundler
sudo: false
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/sinatra.gemfile
matrix:
  exclude:
    # Rails 3 requires Ruby 1.8.7 or newer
    # Rails 4 prefers Ruby 2.0 and requires 1.9.3 or newer
    # Rails 4.1 recommends Ruby 2.1 and requires 1.9.3 or newer
    # Rails 4.2.1 recommends Ruby 2.2 and requires 1.9.3 or newer
    # Rails 5 requires Ruby 2.2.2 or newer
    # Sinatra 2 requires Ruby 2.2.2 or newer
    - rvm: 2.0.0
      gemfile: gemfiles/rails_5.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/sinatra.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/sinatra.gemfile
    # Rails 4 and 4.1 fails with Ruby newer then 2.3
    - rvm: 2.4.3
      gemfile: gemfiles/rails_4.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails_4.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails_4.1.gemfile
before_install:
  - gem install bundler
script:
  - bundle exec rspec
addons:
  code_climate:
    repo_token: e233a382471f480a061ac3098edadbb91cee8129e0938973aeb2aa8d84a0a93b
after_success:
  - bundle exec codeclimate-test-reporter
