name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    env:
      COVERAGE_RUBY_VERSION: 2.6
    strategy:
      matrix:
        ruby:
          - 2.4
          - 2.5
          - 2.6
          - 2.7
          #- truffleruby
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Ruby ${{ matrix.ruby }}
        uses: eregon/use-ruby-action@master
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'

      - name: Install
        run: |
          sudo apt-get -y install libsqlite3-dev
          gem install bundler -v 1.17.3
          bundle _1.17.3_ -v
          bundle install
          bundle _1.17.3_ exec appraisal _1.17.3_ install

      - name: Test
        run: bundle exec appraisal rspec

      - name: Test and publish code coverage
        if: startsWith(env.RUBY_VERSION, env.COVERAGE_RUBY_VERSION)
        uses: paambaati/codeclimate-action@v2.3.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: bundle exec appraisal rspec
