name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    env:
      COVERAGE_RUBY_VERSION: 2.6
      BUNDLER_PATH: vendor/bundle
    strategy:
      matrix:
        ruby:
          - 2.4
          - 2.5
          - 2.6
          - 2.7
          - truffleruby
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Ruby ${{ matrix.ruby }}
        uses: eregon/use-ruby-action@master
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: ${{ env.BUNDLER_PATH }}
          key: bundler-${{ matrix.ruby }}-${{ hashFiles('*.gemspec') }}-${{ hashFiles('**/gemfiles/**') }}

      - name: Install bundler
        run: |
          sudo apt-get -y install libsqlite3-dev libxslt1-dev
          gem uninstall bundler -v '>= 2' -ax --force || true
          gem install bundler -v '~>1.0' -N || true
          echo "Bundler version 1.17.3" | grep -o -E '\d+\.\d+.\d+'
          bundle -v
          bundle -v | grep -o -E '\d+\.\d+.\d+'
          echo "::set-env name=BUNDLER_VERSION::$(bundle -v | grep -o -E '\d+\.\d+.\d+')"

      - name: Install dependencies
        run: |
          bundle config path ${{ env.BUNDLER_PATH }}
          bundle -v
          bundle install
          bundle exec appraisal install

      - name: Test
        run: bundle exec appraisal rspec

      - name: Publish code coverage
        if: startsWith(env.RUBY_VERSION, env.COVERAGE_RUBY_VERSION)
        uses: paambaati/codeclimate-action@v2.3.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: bundle exec appraisal rspec
