name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    env:
      COVERAGE_RUBY_VERSION: 2.6
    strategy:
      matrix:
        ruby:
          - 2.4
          - 2.5
          - 2.6
          - 2.7
          - truffleruby
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Ruby ${{ matrix.ruby }}
        uses: eregon/use-ruby-action@master
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/gemfiles/**') }}-${{ hashFiles('*.gemspec') }}

      - name: Install
        run: |
          sudo apt-get -y install libsqlite3-dev libxslt1-dev
          gem uninstall bundler -v '>= 2' -ax --force || true
          gem install bundler -v '~>1.0' -N || true
          bundle -v
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec appraisal install

      - name: Test
        run: bundle exec appraisal rspec

      - name: Test and publish code coverage
        if: startsWith(env.RUBY_VERSION, env.COVERAGE_RUBY_VERSION)
        uses: paambaati/codeclimate-action@v2.3.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: bundle exec appraisal rspec
